### ISSUE TITLE
Fw Address Group Invalid

### ISSUE THREAD

**Issue by leocf8585** [PaloAltoNetworks/ansible-pan#256] opened 2019-03-12 10:57 UTC
Can not run Fw object or address group, getting the same error.... All modules are installed.

ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/draven/.ansible/roles/paloaltonetworks.paloaltonetworks/examples/fw_address_group.yml': line 12, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  - name: Create static address group
    ^ here

**Comment by SudarshanVK** [comment] 2019-03-12 21:19
1. Have you installed the Galaxy Role necessary?
2. have you called the role in your playbook.
3. execute "ansible-doc -t module fw_address_group" to check if you have the module.

**Comment by leocf8585** [comment] 2019-03-12 22:38
> 
> 
>     1. Have you installed the Galaxy Role necessary?
It is installed and the role is into the script.

 
>     2. have you called the role in your playbook.
yes.

> 
>     3. execute "ansible-doc -t module fw_address_group" to check if you have the module.

When I execute this, panos_address_group or panos_object are missing, how to install the module on the right way?

 ansible-doc -t module panos_object
ERROR! module panos_object has a documentation error formatting or is missing documentation

root@ubuntu:~# ansible-doc -t module panos_address_object
 [WARNING]: module panos_address_object not found in:
/root/.ansible/plugins/modules:/usr/share/ansible/plugins/modules:/usr/local/lib/python2.7
/dist-packages/ansible/modules

**Comment by SudarshanVK** [comment] 2019-03-13 01:58
navigate to the location of your panos modules and wget the .py file https://github.com/PaloAltoNetworks/ansible-pan/tree/develop/library

**Comment by leocf8585** [comment] 2019-03-13 11:01
Even using panos_address_group or panos object module inside the playbook I am getting this error... Only the playbook to add sec rules is working at this moment. 

Error after install the missing module.
----------------------------------------------------------------

ansible-playbook -i ./inventory.ini fw_objects_add.yml 

ERROR! Syntax Error while loading YAML.
  expected <block end>, but found '<block sequence start>'

The error appears to have been in '/home/draven/test_ansible/Palo/fw_objects_add.yml': line 13, column 2, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


 - name: Add an address group to the firewall
 ^ here
----------------------------------------------------------------

Script:

- name: Add some objects to the firewall
  hosts: my-firewall
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'firewall-secrets.yml'

 - name: Add an address group to the firewall
    panos_object:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      addressgroup: 'test-address-group'
      static_value: ['test-address','test-range']
      description: 'This is a test addressgroup'
      operation: 'add'

-----------------------------------------

If I change the ip address or username, the results are the same.

**Comment by shinmog** [comment] 2019-03-19 14:26
@leocf8585 

Could you paste in your playbook with \`\`\` surrounding both sides of it?  So:

```yaml
line1
line2
```

**Comment by leocf8585** [comment] 2019-03-20 17:31
Hi Mate,

It is working now, had to wget the module into ansible modules. But I have pandevice installed, and did not find in there even ansible has the /usr/share on the modules path for ansible. 

Thank you so much.

**Comment by shinmog** [comment] 2019-04-06 00:38
Ok, closing as the issue is resolved.

**Closed by shinmog** 2019-04-06 00:38 UTC
