### ISSUE TITLE
Can't find the right XPATH

### ISSUE THREAD

**Issue by MrNN** [PaloAltoNetworks/ansible-pan#27] opened 2017-08-29 13:41 UTC
I am trying to configure some address objects using this module for ansible. When I run the playbook everything except adding the address object is fine. 
This is my task:
 `tasks`:
`    - name: Add an address object to Panorama`
`      panos_object:`
`        ip_address: '{{ ip_address }}'`
`        username: '{{ username }}'`
`        password: '{{ password }}'`
`        addressobject: 'Test_Address_Object'`
`        address: '{{ item[1] }}'`
`        address_type: 'ip-netmask'`
`        description: '{{ item[2] }}'`
`        devicegroup: 'Test_Device_Group'`
`        operation: 'add'`
`      with_items:`
`        - "{{ tmpdata }}"`

This is the output that I get:

> "msg": "Could not find schema node for xpath /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/address\n"

I am using Python 2.7 and a Panorama M500 appliance with PAN-OS 8.0.4

**Comment by zuesmajor** [comment] 2017-08-30 21:29
getting the same error on NAT rule

`"msg": "Could not find schema node for xpath /config/devices/entry[@name='localhost.localdomain']/rulebase/nat/rules\n"`

**Comment by shinmog** [comment] 2017-08-30 21:54
That second xpath error is caused by PaloAltoNetworks/pandevice#93 - we've fixed it in develop, and will create a new 0.5.1 release soon.

**Comment by zuesmajor** [comment] 2017-08-30 21:55
Thanks!

**Comment by zuesmajor** [comment] 2017-08-31 15:54
@shinmog Thanks! How do I get updates on new versions? Or should I just keep checking with `pip install update pandevice`

**Comment by shinmog** [comment] 2017-08-31 17:03
@MrNN - What is the value of `model` for you that that updated fixed it?

@zuesmajor - Yeah, this is affecting both security policies and NAT policies.  You can grab pandevice from the develop branch to get the fixes, otherwise I'll make a new pandevice soon.  I will update this bug and tag you so you know.

**Comment by MrNN** [comment] 2017-08-31 18:56
@shinmog - When I execute the command `show system info` in the Panorama CLI, the output for `model ` is `M-500`. Because I think (cannot confirm it) a Panorama M-100 appliance would give an output of `M-100` I changed the statement from `if model == "Panorama":` to `if model == "Panorama" or "M-" in model:`.
I just added `or "M-" in model` to the if-statement.

~ MrNN

**Comment by zuesmajor** [comment] 2017-08-31 20:49
@MrNN when I execute `show system info`, would there have to be multiple checks done for devices? Asknig because i'm using a PA-220

**Comment by MrNN** [comment] 2017-08-31 21:01
@zuesmajor probably not. If I understood the source code right, there is only a differentiation between Panorama and firewalls so no differentiation between the varieties/models of the firewalls. As far as I know there shouldn't be any difference in software/firmware between two different models (e.g. PA-220 and PA-850) if they run on the same PAN-OS version. The only difference there should be the hardware specifications. I am not 100% sure on that; better let it be confirmed by a PAN technician.

~ MrNN

**Comment by shinmog** [comment] 2017-08-31 21:12
Correct, the only hardware distinction is between firewalls and panorama.

**Comment by ivanbojer** [comment] 2017-08-31 21:23
Given that this is issue in the underlying library closing ansible. Please refer to this from now on:
https://github.com/PaloAltoNetworks/pandevice/issues

**Closed by ivanbojer** 2017-08-31 21:23 UTC

**Comment by BenVicuna** [comment] 2019-04-10 19:18
Hey people, am still having the issue "fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed \"add\" create: Could not find schema node for xpath /config/shared/rulebase/pre-rulebase/security/rules\n"}"
when installing security policy on a device group in Panorama. Is anyone having the same issue?

**Comment by shinmog** [comment] 2019-04-10 19:54
Hrm, I think that there is no rulebase under the shared namespace...  This means you should specify a device group instead of leaving that parameter empty.

**Comment by BenVicuna** [comment] 2019-04-10 21:11
This is what am using :

  - name: add SSH inbound rule to Panorama device group
    panos_security_rule:
     ip_address: "{{ panorama }}"
     username: "{{ account }}"
     password: "{{ password }}"
     rule_name: 'SSH permit'
     description: 'SSH rule test'
     source_zone: ['int-01']
     source_ip: ['any']
     destination_zone: ['out-01']
     destination_ip: ['1.1.1.1']
     application: ['ssh']
     action: 'allow'
     devicegroup: 'AMER-ITC-XXXXXXFNP51'
     rulebase: 'pre-rulebase'

**Comment by shinmog** [comment] 2019-04-10 21:16
Add `state: 'present'` to that task, what happens?

**Comment by BenVicuna** [comment] 2019-04-10 21:18
Ouch! Still the same man. Why is Ansible looking for the wrong xpath?

It should be : **/config/shared/pre-rulebase/security/rules** and not /config/shared/rulebase/pre-rulebase/security/rules

**Comment by shinmog** [comment] 2019-04-10 21:22
At this point, please open a new defect, this is a closed issue.

In that new defect, can you please paste the playbook that shows you're using the Ansible Galaxy role as well as the above?  For formatting niceties, please do triple ticks around the playbook to preserve formatting.
