### ISSUE TITLE
panos_static_route is broken.  Nexthop required but option does not exist.

### ISSUE THREAD

**Issue by dpflick** [PaloAltoNetworks/ansible-pan#345] opened 2019-04-24 22:09 UTC
Variables:

```
routes:
  - name: 'ECATS-L2L-172.16.1'
    destination: '172.16.1.0/24'

  - name: 'ECATS-L2L-172.16.3'
    destination: '172.16.3.0/24'

  - name: 'ECATS-L2L-172.16.251'
    destination: '172.16.251.0/24'

  - name: 'ECATS-L2L-64.58.49.249'
    destination: '64.58.49.249/32'
```

Task:

```
- name: Building routes for tunnel
  panos_static_route:
    ip_address: '{{ fw_ip_address }}'
    username: '{{ fw_username }}'
    password: '{{ fw_password }}'
    virtual_router: '{{ vrouter }}'
    name: '{{ item.name }}'
    destination: '{{ item.destination }}'
    interface: 'tunnel.80'
  with_items:
    - '{{ routes }}'
```

Error:

failed: [atcog-tc-vpnfw] (item={u'destination': u'172.16.1.0/24', u'name': u'ECATS-L2L-172.16.1'}) => {"changed": false, "item": {"destination": "172.16.1.0/24", "name": "ECATS-L2L-172.16.1"}, "msg": " ECATS-L2L-172.16.1 -> nexthop is invalid"}
failed: [atcog-tc-vpnfw] (item={u'destination': u'172.16.3.0/24', u'name': u'ECATS-L2L-172.16.3'}) => {"changed": false, "item": {"destination": "172.16.3.0/24", "name": "ECATS-L2L-172.16.3"}, "msg": " ECATS-L2L-172.16.3 -> nexthop is invalid"}
failed: [atcog-tc-vpnfw] (item={u'destination': u'172.16.251.0/24', u'name': u'ECATS-L2L-172.16.251'}) => {"changed": false, "item": {"destination": "172.16.251.0/24", "name": "ECATS-L2L-172.16.251"}, "msg": " ECATS-L2L-172.16.251 -> nexthop is invalid"}
failed: [atcog-tc-vpnfw] (item={u'destination': u'64.58.49.249/32', u'name': u'ECATS-L2L-64.58.49.249'}) => {"changed": false, "item": {"destination": "64.58.49.249/32", "name": "ECATS-L2L-64.58.49.249"}, "msg": " ECATS-L2L-64.58.49.249 -> nexthop is invalid"}

Searching through the module, nexthop nor next_hop exists in the code.

**Comment by shinmog** [comment] 2019-04-25 16:21
@dpflick 

The nexthop param [is there](https://github.com/PaloAltoNetworks/ansible-pan/blob/master/library/panos_static_route.py#L177), and is documented in the module documentation.

You're using the Ansible Galaxy [role](https://galaxy.ansible.com/PaloAltoNetworks/paloaltonetworks), correct?

**Comment by dpflick** [comment] 2019-05-02 14:43
I am in the development branch.  I searched the task file and could not find a reference in the development branch.   I was using the development branch for the BGP tasks.

**Comment by shinmog** [comment] 2019-05-06 14:15
@dpflick 
Taking another look at the error, it seems PAN-OS is complaining about the configuration, not the module is giving you errors.  Your problem is a PAN-OS problem.  I'm thinking basic config issue like "tunnel.80 isn't attached to the vrouter" type of stuff.

Maybe try and add one static route using the GUI to determine what is happening..?

**Comment by shinmog** [comment] 2019-06-11 23:36
Assuming the issue is resolved, closing issue.

**Closed by shinmog** 2019-06-11 23:36 UTC
