### ISSUE TITLE
Feature Request: Configure aggregate-group properties

### ISSUE THREAD

**Issue by metroshica** [PaloAltoNetworks/ansible-pan#404] opened 2019-06-24 16:43 UTC
Unless I'm missing something in the documentation, I don't seem to be able to create an aggregate group or configure any of its properties. My use-case is creating an aggregate group and then creating l3 subinterfaces. I've looked through the docs and have found that I can add an interface to the group using the aggregate_group property in the panos_interface module. However, that seems to be about the extent of what I can do. If I change the if_name in the panos_interface module to ae1 for example, I get the error "Failed create:  ae1 'ae1' is not a valid reference". If I'm missing something obvious here, please let me know, but from the docs is doesn't seem that this is currently possible.

**Comment by metroshica** [comment] 2019-06-25 13:37
I'm also unable to configure properties of a subinterface on an aggregate group using panos_l3_subinterface. For example, when I try and create a subinterface on ae1, I get the error message: "Failed refresh: Object doesn't exist: /config/devices/entry[@name='localhost.localdomain']/network/interface/ethernet/entry[@name='ae1']"

**Comment by shinmog** [comment] 2019-06-28 20:17
@metroshica 
Aggregate interfaces are in a different XPATH from regular ethernet interfaces; there will need to be a `panos_aggregate_interface` module to support this.

**Comment by odysseus107** [comment] 2019-09-06 01:25
I made a proposal (pull request). Please comment as it does not yet work completely as intended.

https://github.com/PaloAltoNetworks/ansible-pan/pull/428

**Comment by k4le0** [comment] 2019-10-24 23:02
Similar issue. 

  - name: Create subinterface
    panos_l3_subinterface:
      provider: '{{ provider }}'
      name: 'ae1.111'
      tag: '111'
      enable_dhcp: 'false'
      ip: ["10.0.0.1/24"]
      zone_name: 'vendor'
      vsys: 'vsys3'
      vr_name: 'VENDOR' 
      management_profile: 'icmp'
      ipv6_enabled: 'false'

Gives following error message:
FAILED! => {"changed": false, "msg": "Failed refresh: Object doesn't exist: /config/devices/entry[@name='localhost.localdomain']/network/interface/ethernet/entry[@name='ae1']"}

**Comment by shinmog** [comment] 2020-01-16 20:27
Between @odysseus107 PR #428 and looking at the code in `panos_l3_subinterface`, this should be resolved.  If a name is specified that starts with `ae` then the parent interface will be an aggregate interface instead of an ethernet interface.

Closing this issue.

**Closed by shinmog** 2020-01-16 20:27 UTC
