### ISSUE TITLE
Cannot use named ip in panos_ike_gateway

### ISSUE THREAD

**Issue by pixelicous** [PaloAltoNetworks/ansible-pan#217] opened 2019-01-10 17:08 UTC
I am trying to use local_ip_address with an object name in ike gateway
It creates the ike gateway but it doesnt assign any local ip address
Something like this does work for example a "panos_interface"
```

  - name: Add IKE gateway config to the firewall
    panos_ike_gateway:
      ip_address: '{{ fw_ip_address2 }}'
      username: '{{ fw_username }}'
      password: '{{ fw_password }}'
      name: 'IKE-GW-To-Local'
      protocol_version: 'ikev2'
      interface: 'loopback.2'
      liveness_check: '5'
      peer_ip_value: 'MY-GW'
      **local_ip_address: ['untrust-vip']**
      passive_mode: False
      psk: some_key
      crypto_profile_name: 'default'
      commit: False
      state: 'present'
```

**Comment by geraint-jones-nz** [comment] 2019-02-21 01:05
Have you tired 
```local_ip_address_type: floating-ip
local_ip_address: 'untrust-vip'`

**Comment by pixelicous** [comment] 2019-04-03 10:43
@geraint-jones-nz thanks for the input! i will try

**Comment by shinmog** [comment] 2019-06-11 23:36
Assuming the issue is resolved, closing issue.

**Closed by shinmog** 2019-06-11 23:36 UTC
